### ISSUE TITLE
Help with exception handling for edit command

### ISSUE THREAD

**Issue by eugenelim97** [AY1920S1-CS2113T-T12-3/main#218]
For eg. flour already exists in shopping list.
Then, I edit another ingredient's name to flour, I would not be able to enter. (I want an exception)

I tried to call a duplicateEntity exception which compares the toEdit and edited, but in this way, quantity cannot be edited as the new constructor also has the same name.

Anyone knows how to work around this?

**Comment by liujiajun** [comment]
Sorry I didn't get your question. From my testing, I can't add ingredients with duplicate names. Also, I'm able to edit ingredient names and qtys

**Comment by liushiru** [comment]
Edit an inventory/shopping list item to have the same name as another item will throw an error. Is that what you mean?

**Comment by liushiru** [comment]
Sorry I'm not sure whether the above-mentioned issue is the problem you encountered. But what I would do to solve that problem is to add a try-catch block in EditInventoryCommand.java. Hope it helps.
![image](https://user-images.githubusercontent.com/42794162/68001157-d67b9880-fc9d-11e9-94e4-715d1940c925.png)
